### ISSUE TITLE
Typekit font is hotfixed with a hack

### ISSUE THREAD

**Issue by naps62** [subvisual/blog.subvisual.co#103]
I had to push this quickfix: https://github.com/subvisual/blog.subvisual.co/commit/4e2fa4286814ddc19af5ef927e4d0d5a36a8d083

because the font wasn't being loaded properly
The problem, from what I could see is that the current markup includes:

```
<html class="Theme ... wf-active">
```

where wf-active is the class automatically added by typekit. But when defining the font for the Theme, we're querying for `.wf-active .Theme`, which obviously doesn't match

@azevedo-252 do you know something about this? I don't remember having seen that query at the time I worked on this

**Comment by azevedo-252** [comment]
What does "loaded properly" mean?
The ideia was to use a fallback font while typekit doesn't load. This way there's a flash of unstyled text instead of, in some browsers, not rendering the text at all.
At the time this was discussed and agreed that a FOUT was better than no text at all.
I don't know what you experienced, but if it was this, then I believe this hotfix should be reverted.

**Comment by naps62** [comment]
By loaded properly I mean the font was not being used on the blog at all

If this was agreed, then changes to the blog CSS should have been done back then. Or even better, some versioning system should exist on blue so that this doesn't happen. The current build process forces me to copy&paste everything from blue. Which, if you're going to make breaking changes like this, is a problem

The hotfix should obviously be reverted, but only when a proper fix is implemented. Since I didn't really knew the reasons for that, or a proper solution, I had to go with the fastest one I could find

**Comment by azevedo-252** [comment]
Sure. So what's the next step then?

**Comment by naps62** [comment]
Actually I just noticed that this might be a bug in blue itself.

The blog was relying on this rule from blue to apply the correct font:
https://github.com/subvisual/blog.subvisual.co/blob/master/vendor/assets/blue/stylesheets/blue/components/_theme.scss

But with that change to a FOUT, this applies the font to `@at-root.wf-active .Theme`, which doesn't exist (both classes are on the same element).
Shouldn't that just be changed to `&.wf-active` ?

**Comment by azevedo-252** [comment]
That indeed does not work, although your proposal doesn't fix it because we still need to overwrite every font-family definition which happens in that mixin. So, instead, an extra rule should be created to match `.wf-active.Theme` but outside the mixin, otherwise those rules would be uselessly copied every time the mixin was invoked.

The reason why this bug was not noticed, is because we're not relying on the font-family being inherited from `<html>`.
